# .github/workflows/main.yml

name: Automação YouTube

# Agendamento para 6 AM e 6 PM UTC diariamente
on:
  schedule:
    - cron: '0 6 * * *'   # 6:00 AM UTC
    - cron: '0 18 * * *'  # 6:00 PM UTC
  workflow_dispatch:      # Permitir execução manual, se necessário

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permite que o workflow faça commit e push

    steps:
    # Passo 1: Checkout do Repositório
    - uses: actions/checkout@v3

    # Passo 2: Configurar o Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Ajuste conforme necessário

    # Passo 3: Instalar Dependências
    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    # Passo 4: Configurar Git
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Passo 5: Criar Arquivo client_secret.json a partir do Segredo Base64
    - name: Create Client Secret File
      run: |
        echo "${{ secrets.CLIENT_SECRET_FILE_FIZZQUIRK }}" | base64 --decode > client_secret.json

    # Passo 6: Criar Arquivo token.json a partir do Segredo Base64
    - name: Create Token File
      run: |
        echo "${{ secrets.TOKEN_FILE_FIZZQUIRK }}" | base64 --decode > token.json

    # Passo 7: Gerar Vídeo
    - name: Generate Video
      id: generate_video
      run: |
        source venv/bin/activate
        echo ">>> pip freeze debug:"
        pip freeze

        # Gera vídeo
        python scripts/main.py \
          --gemini-api "$GEMINI_API_KEY" \
          --youtube-channel "$YOUTUBE_CHANNEL_ID" \
          --pixabay-api "$PIXABAY_API_KEY" \
          --quantidade 5  # Ajuste o número de curiosidades conforme necessário
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}

    # Passo 8: Fazer Upload no YouTube (Só se o Passo Anterior Tiver Sucesso)
    - name: Upload to YouTube
      if: success() && steps.generate_video.outcome == 'success'
      run: |
        source venv/bin/activate

        python scripts/upload_youtube.py \
          --video-file "video_final.mp4" \
          --client-secret-file "client_secret.json" \
          --token-file "token.json" \
          --title "Curiosidades do Dia" \
          --description "Confira essas curiosidades incríveis!" \
          --category "22" \
          --tags "curiosidades,fatos,informação"
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
