name: Automação de Vídeos para YouTube

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Create Venv and Install Deps
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir moviepy
        shell: bash

      - name: List Installed Packages
        run: |
          source venv/bin/activate
          pip list
        shell: bash

      - name: Check MoviePy Version
        run: |
          source venv/bin/activate
          python -c "import moviepy; print(moviepy.__version__)"
        shell: bash

      # 4. Optional - Install Fonts for Pillow
      - name: Install Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core fonts-dejavu-extra
        shell: bash

      # 5. Decode Secrets (caso seja preciso)
      - name: Decode Secrets
        run: |
          mkdir -p credentials
          echo "${{ secrets.CLIENT_SECRET_FILE_FIZZQUIRK }}" | base64 --decode > credentials/client_secret.json
          echo "${{ secrets.TOKEN_FILE_FIZZQUIRK }}" | base64 --decode > credentials/token.json
          ls -lh credentials/
        shell: bash

      # 6. Environment Variables
      - name: Set Env
        run: |
          echo "IMAGEMAGICK_BINARY=/bin/false" >> $GITHUB_ENV
          # etc.
        shell: bash

      # 7. Run Script
      - name: Run Main Script
        run: |
          source venv/bin/activate
          python scripts/main.py
        shell: bash
