name: Pipeline de Automação

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1) Baixar o código
      - name: Checkout do Código
        uses: actions/checkout@v3

      # Passo 2) Definir versão do Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Passo 3) Unificar instalação + execução em um só passo
      - name: Install & Run
        run: |
          # 1. Desativar ImageMagick
          echo "IMAGEMAGICK_BINARY=/bin/false" >> $GITHUB_ENV

          # 2. Executar SEU script de instalação (que deve criar/ativar venv e instalar dependências)
          #   Ajuste conforme o nome real do seu script .sh ou .py
          bash scripts/install_dependencies.sh

          # 3. Executar SEU script principal (assumindo que ele usa o venv ativado pelo script anterior)
          python scripts/main.py
        shell: bash
