name: Automação YouTube

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do Repositório
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Especifica a versão do Python

      # Passo 3: Instalar Dependências
      - name: Instalar Dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Configurar Git
      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Passo 5: Criar Pasta de Credenciais
      - name: Criar Pasta de Credenciais
        run: mkdir -p credentials

      # Passo 6: Decodificar Service Account JSON
      - name: Decodificar Service Account JSON
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 --decode | sed '1s/^\xEF\xBB\xBF//' > credentials/client_secret.json

      # Passo 7: Instalar jq para Validar JSON
      - name: Instalar jq para Validar JSON
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Passo 8: Validar Estrutura do service_account.json
      - name: Validar Estrutura do service_account.json
        run: jq empty credentials/client_secret.json

      # Passo 9: Verificar Presença do Campo 'token_uri' no service_account.json
      - name: Verificar Presença do Campo 'token_uri' no service_account.json
        run: |
          if jq -e '.token_uri' credentials/client_secret.json > /dev/null; then
            echo "'token_uri' está presente."
          else
            echo "Erro: Campo 'token_uri' está ausente no service_account.json."
            exit 1
          fi

      # Passo 10: Verificar Presença do Campo 'client_email' no service_account.json
      - name: Verificar Presença do Campo 'client_email' no service_account.json
        run: |
          if jq -e '.client_email' credentials/client_secret.json > /dev/null; then
            echo "'client_email' está presente."
          else
            echo "Erro: Campo 'client_email' está ausente no service_account.json."
            exit 1
          fi

      # Passo 11: Executar Script de Automação
      - name: Executar Script de Automação
        run: |
          source venv/bin/activate
          # Verifica se todas as variáveis de ambiente estão definidas
          if [ -z "$GEMINI_API_KEY" ] || [ -z "$YOUTUBE_CHANNEL_ID" ] || [ -z "$PIXABAY_API_KEY" ]; then
            echo "Erro: Uma ou mais variáveis de ambiente estão vazias."
            exit 1
          fi
          # Executa o script principal com os parâmetros necessários
          python scripts/main.py \
            --gemini-api "${GEMINI_API_KEY}" \
            --youtube-channel "${YOUTUBE_CHANNEL_ID}" \
            --pixabay-api "${PIXABAY_API_KEY}" \
            --quantidade 3  # Atualizado para 3 para atender aos requisitos da API

      # Passo 12: Finalizar Job
      - name: Finalizar Job
        if: always()
        run: echo "Job finalizado."
