name: Automação de Vídeos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install --upgrade -r requirements.txt

      - name: Decodificar client_secret.json.base64
        run: |
          base64 -d credentials/canal1_client_secret.json.base64 > credentials/client_secret.json

      - name: Verificar Presença do Campo 'token_uri' no client_secret.json
        if: success()
        run: |
          if jq -e '.token_uri' credentials/client_secret.json > /dev/null; then
            echo "'token_uri' está presente."
          else
            echo "Erro: Campo 'token_uri' está ausente no client_secret.json."
            exit 1
          fi

      - name: Executar Script de Automação
        run: |
          python scripts/main.py --video-title "<titulo_do_video>" --audio-file "<caminho/para/o/audio.mp3>"
