name: Automação YouTube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Create Client Secret File
      run: |
        echo "${{ secrets.CLIENT_SECRET_FILE_FIZZQUIRK }}" | base64 --decode > client_secret.json

    - name: Create Token File
      run: |
        echo "${{ secrets.TOKEN_FILE_FIZZQUIRK }}" | base64 --decode > token.json

    - name: Generate Video
      run: |
        source venv/bin/activate
        python scripts/main.py \
          --gemini-api "$GEMINI_API_KEY" \
          --youtube-channel "$YOUTUBE_CHANNEL_ID" \
          --pixabay-api "$PIXABAY_API_KEY" \
          --quantidade "$QUANTIDADE" | tee main_output.log

    - name: Verify Video Generation
      run: |
        if [ ! -f "video_final.mp4" ]; then
          echo "Erro: O arquivo de vídeo 'video_final.mp4' não foi encontrado."
          exit 1
        fi

    - name: Listar Arquivos Após Geração do Vídeo
      run: |
        echo ">>> Listando arquivos no diretório atual:"
        ls -la
        echo ">>> Listando arquivos no diretório de saída (se houver):"
        if [ -d "output" ]; then
          ls -la output/
        else
          echo "Diretório 'output' não encontrado."
        fi
        echo ">>> Verificando a existência de 'video_final.mp4':"
        ls -la | grep video_final.mp4 || echo "Arquivo 'video_final.mp4' não encontrado."

    - name: Exibir Logs da Geração do Vídeo
      run: |
        echo ">>> Exibindo logs da geração do vídeo:"
        cat main_output.log

    - name: Verificar Dependências Instaladas
      run: |
        source venv/bin/activate
        pip list

    - name: Upload to YouTube
      if: success() && steps.generate_video.outcome == 'success'
      run: |
        source venv/bin/activate
        python scripts/upload_youtube.py \
          --video-file "video_final.mp4" \
          --client-secret-file "client_secret.json" \
          --token-file "token.json" \
          --title "Curiosidades do Dia" \
          --description "Confira essas curiosidades incríveis!" \
          --category "22" \
          --tags "curiosidades,fatos,informação"
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    - name: Post Set up Python
      if: always()
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
