name: Pipeline de Automação

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1) Baixar o código
      - name: Checkout do Código
        uses: actions/checkout@v3

      # Passo 2) Definir versão do Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Passo 3) Instalar dependências E rodar script no MESMO passo
      - name: Install & Run
        run: |
          # 1. Desativar ImageMagick (opcional, caso queira forçar uso do Pillow)
          echo "IMAGEMAGICK_BINARY=/bin/false" >> $GITHUB_ENV

          # 2. Criar e ativar um ambiente virtual
          python -m venv venv
          source venv/bin/activate

          # 3. Instalar dependências (requirements.txt deve estar na raiz do repo)
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

          # 4. (Opcional) Instalar manualmente se quiser garantir MoviePy/Pillow
          # pip install --no-cache-dir moviepy pillow

          # 5. Executar seu script principal
          python scripts/main.py
        shell: bash
