name: Automação YouTube

on:
  workflow_dispatch:  # Permite execução manual
  push:
    branches:
      - main  # Executa no push para main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3
      # Remova o with com working-directory, se houver

    # Decodifica os arquivos ANTES de configurar o Python e instalar dependências.
    # NOTA: Mantenha este passo ANTES da instalação de dependências,
    # pois o script de decodificação (openssl) é um comando do sistema
    # e não depende do ambiente Python.
    - name: Decodificar client_secret.json.base64 e token.json.base64
      run: |
        # Certifique-se de que a pasta credentials existe
        mkdir -p credentials
        openssl base64 -d -in credentials/canal1_client_secret.json.base64 -out credentials/client_secret.json
        openssl base64 -d -in credentials/canal1_token.json.base64 -out credentials/token.json

    # --- NOVOS PASSOS DE INSPEÇÃO ---
    # Estes passos vão imprimir o início dos arquivos decodificados no log para debug
    - name: Inspecionar client_secret.json decodificado
      run: |
        echo "--- Conteúdo de credentials/client_secret.json (Primeiros 20 bytes em Hex)"
        # Usa head para pegar os primeiros 20 bytes e hexdump para mostrá-los em hex
        head -c 20 credentials/client_secret.json | hexdump -C
        echo "--- Conteúdo de credentials/client_secret.json (Completo)"
        # Usa cat para imprimir o conteúdo completo (pode ser útil para ver o JSON)
        cat credentials/client_secret.json
        echo "--- Fim da inspeção de client_secret.json"
      # Use continue-on-error: true para que o workflow não pare aqui, mesmo que algo dê errado
      # na inspeção (ex: arquivo não encontrado, embora improvável após a decodificação).
      continue-on-error: true

    - name: Inspecionar token.json decodificado
      run: |
        echo "--- Conteúdo de credentials/token.json (Primeiros 20 bytes em Hex)"
        head -c 20 credentials/token.json | hexdump -C
        echo "--- Conteúdo de credentials/token.json (Completo)"
        cat credentials/token.json
        echo "--- Fim da inspeção de token.json"
      continue-on-error: true
    # --- FIM DOS NOVOS PASSOS ---

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Limpar cache do pip
      # O cache do pip é separado por versão do Python, limpar pode ser útil
      # após configurar a versão do Python.
      run: pip cache purge

    - name: Instalar dependências
      # Este passo agora virá DEPOIS da decodificação e inspeção
      run: pip install --upgrade -r requirements.txt

    - name: Executar Script de Automação
      # Este passo virá DEPOIS da decodificação, inspeção e instalação
      run: python scripts/main.py --channel "fizzquirk"
