name: Automação de Vídeos no YouTube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    # 1. Checkout do repositório
    - name: Checkout do Repositório
      uses: actions/checkout@v3

    # 2. Configurar Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Versão do Python a ser usada

    # 3. Instalar Dependências
    - name: Instalar Dependências
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Configurar Git
    - name: Configurar Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # 5. Criar Pasta de Credenciais
    - name: Criar Pasta de Credenciais
      run: mkdir -p credentials

    # 6. Decodificar Client Secret com Remoção de BOM
    - name: Decodificar Client Secret
      run: |
        echo "${{ secrets.CLIENT_SECRET_FILE_FIZZQUIRK }}" | base64 --decode | sed '1s/^\xEF\xBB\xBF//' > credentials/client_secret.json
      env:
        CLIENT_SECRET_FILE_FIZZQUIRK: ${{ secrets.CLIENT_SECRET_FILE_FIZZQUIRK }}

    # 7. Decodificar Token com Remoção de BOM
    - name: Decodificar Token
      run: |
        echo "${{ secrets.TOKEN_FILE_FIZZQUIRK }}" | base64 --decode | sed '1s/^\xEF\xBB\xBF//' > credentials/token.json
      env:
        TOKEN_FILE_FIZZQUIRK: ${{ secrets.TOKEN_FILE_FIZZQUIRK }}

    # 8. Instalar jq para Validar JSON
    - name: Instalar jq para Validar JSON
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    # 9. Validar Estrutura do client_secret.json
    - name: Validar Estrutura do client_secret.json
      run: jq empty credentials/client_secret.json

    # 10. Validar Estrutura do token.json
    - name: Validar Estrutura do token.json
      run: jq empty credentials/token.json

    # 11. Verificar Presença do Campo 'token_uri' no client_secret.json
    - name: Verificar Presença do Campo 'token_uri' no client_secret.json
      run: |
        if jq -e '.installed.token_uri' credentials/client_secret.json > /dev/null; then
          echo "'token_uri' está presente."
        else
          echo "Erro: Campo 'token_uri' está ausente no client_secret.json."
          exit 1
        fi

    # 12. Verificar Presença do Campo 'client_email' no client_secret.json
    - name: Verificar Presença do Campo 'client_email' no client_secret.json
      run: |
        if jq -e '.installed.client_email' credentials/client_secret.json > /dev/null; then
          echo "'client_email' está presente."
        else
          echo "Erro: Campo 'client_email' está ausente no client_secret.json."
          exit 1
        fi

    # 13. Outras Etapas do Workflow
    # Adicione aqui outras etapas necessárias para a sua automação, por exemplo:
    # - Nome: Executar Script de Automação
    #   run: |
    #     source venv/bin/activate
    #     python seu_script.py

    # 14. Post Checkout do Repositório (Sempre Executado)
    - name: Post Checkout do Repositório
      if: always()
      run: |
        echo "Finalizando o checkout do repositório."
      # Esta etapa pode incluir ações de limpeza ou outras finalizações necessárias

    # 15. Post Configurar Python (Sempre Executado)
    - name: Post Configurar Python
      if: always()
      run: |
        echo "Finalizando a configuração do Python."
      # Esta etapa pode incluir ações de limpeza ou outras finalizações necessárias
