# .github/workflows/main.yml

name: Automação de Vídeos para YouTube

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # Diariamente às 05:00 UTC
    - cron: '0 19 * * *' # Diariamente às 19:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do Código
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Passo 2: Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Passo 3: Instalar Dependências Python
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      # Passo 3.1: Listar Pacotes Instalados
      - name: List Installed Packages
        run: |
          pip list
        shell: bash

      # Passo 3.2: Verificar Versão do MoviePy
      - name: Check MoviePy Version
        run: |
          python -c "import moviepy; print(moviepy.__version__)"
        shell: bash

      # Passo 4: Instalar Fontes Necessárias (Opcional)
      - name: Install Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core fonts-dejavu-extra
        shell: bash

      # Passo 5: Decodificar e Criar Arquivos de Credenciais para Cada Canal
      - name: Decode Secrets and Create JSON Files
        run: |
          mkdir -p credentials
          # Decodificar client_secret.json
          echo "${{ secrets.CLIENT_SECRET_FILE_FIZZQUIRK }}" | base64 --decode > credentials/canal1_client_secret.json
          # Decodificar token.json
          echo "${{ secrets.TOKEN_FILE_FIZZQUIRK }}" | base64 --decode > credentials/canal1_token.json

          # Verificar o tamanho dos arquivos decodificados
          echo "Verificando o tamanho dos arquivos de credenciais:"
          ls -lh credentials/
        shell: bash

      # Passo 5.1: Verificar os Arquivos Decodificados (Depuração)
      - name: Verify Credentials Files
        run: |
          if [ -s credentials/canal1_client_secret.json ]; then
            echo "client_secret.json foi decodificado com sucesso."
          else
            echo "Erro: client_secret.json está vazio ou não foi criado corretamente."
            exit 1
          fi

          if [ -s credentials/canal1_token.json ]; then
            echo "token.json foi decodificado com sucesso."
          else
            echo "Erro: token.json está vazio ou não foi criado corretamente."
            exit 1
          fi
        shell: bash

      # Passo 6: Configurar Variáveis de Ambiente
      - name: Set Environment Variables
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> $GITHUB_ENV
          echo "YOUTUBE_CHANNEL_ID=${{ secrets.YOUTUBE_CHANNEL_ID }}" >> $GITHUB_ENV
        shell: bash

      # Passo 6.1: Desativar ImageMagick
      - name: Disable ImageMagick
        run: |
          echo "IMAGEMAGICK_BINARY=/bin/false" >> $GITHUB_ENV
        shell: bash

      # Passo 7: Executar o Script Principal
      - name: Run Main Script
        run: |
          python scripts/main.py
        shell: bash

      # Passo 8: Upload dos Vídeos Gerados (Opcional)
      - name: Upload Generated Videos
        uses: actions/upload-artifact@v3
        with:
          name: generated_videos
          path: generated_videos/
          if-no-files-found: warn
          include-hidden-files: false

      # Passo 9: Upload de Logs (Opcional)
      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs/main.log
          if-no-files-found: warn
          include-hidden-files: false
