name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # 1) Checkout do repositório
    - name: Checkout do Código
      uses: actions/checkout@v3

    # 2) Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # 3) Instala e Executa
    - name: Install & Run
      run: |
        # (Opcional) Desabilitar ImageMagick, caso MoviePy tente invocar 'convert'
        echo "IMAGEMAGICK_BINARY=/bin/false" >> $GITHUB_ENV

        # Criar e ativar venv
        python -m venv venv
        source venv/bin/activate

        # Atualiza pip
        pip install --upgrade pip

        # Instalar pacotes
        pip install --no-cache-dir -r requirements.txt

        # (Opcional) Mostrar libs instaladas
        echo ">>> pip freeze debug:"
        pip freeze

        # Rodar script principal
        python scripts/main.py
