jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create Client Secret File
        run: |
          echo "${{ secrets.CLIENT_SECRET_FILE_FIZZQUIRK }}" | base64 --decode > client_secret.json

      - name: Create Token File
        run: |
          echo "${{ secrets.TOKEN_FILE_FIZZQUIRK }}" | base64 --decode > token.json

      - name: Generate Video
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
          QUANTIDADE: ${{ secrets.QUANTIDADE }}
        run: |
          source venv/bin/activate
          python scripts/main.py \
            --gemini-api "$GEMINI_API_KEY" \
            --youtube-channel "$YOUTUBE_CHANNEL_ID" \
            --pixabay-api "$PIXABAY_API_KEY" \
            --quantidade "$QUANTIDADE" | tee main_output.log

      - name: Verify Video Generation
        run: |
          if [ ! -f "video_final.mp4" ]; then
            echo "Erro: O arquivo de vídeo 'video_final.mp4' não foi encontrado."
            exit 1
          fi

      # Outros passos...
