name: Automação YouTube

on:
  workflow_dispatch:  # Permite execução manual
  push:
    branches:
      - main  # Executa no push para main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    # Decodifica os arquivos ANTES de configurar o Python e instalar dependências.
    - name: Decodificar client_secret.json.base64 e token.json.base64
      run: |
        openssl base64 -d -in credentials/canal1_client_secret.json.base64 -out credentials/client_secret.json
        openssl base64 -d -in credentials/canal1_token.json.base64 -out credentials/token.json

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: pip install --upgrade -r requirements.txt

    - name: Executar Script de Automação
      run: python scripts/main.py --channel "fizzquirk"
