name: Automação YouTube

# Agendamento para 5 AM e 7 PM UTC diariamente
on:
  schedule:
    - cron: '0 5 * * *'   # 5:00 AM UTC
    - cron: '0 19 * * *'  # 7:00 PM UTC
  workflow_dispatch:      # Permitir execução manual, se necessário

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do Repositório
    - uses: actions/checkout@v3

    # Passo 2: Configurar o Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Ajuste conforme necessário

    # Passo 3: Instalar Dependências
    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    # Passo 4: Criar Arquivo client_secret.json a partir do Segredo Base64
    - name: Create Client Secret File
      run: |
        echo "${{ secrets.CLIENT_SECRET_FILE_FIZZQUIRK }}" | base64 --decode > client_secret.json

    # Passo 5: Criar Arquivo token.json a partir do Segredo Base64
    - name: Create Token File
      run: |
        echo "${{ secrets.TOKEN_FILE_FIZZQUIRK }}" | base64 --decode > token.json

    # Passo Opcional: Verificar os Arquivos Criados (Para Depuração)
    # **Remova este passo após verificar que os arquivos estão corretos**
    - name: Verify JSON Files
      run: |
        echo "Verificando os primeiros 10 caracteres de client_secret.json:"
        head -c 10 client_secret.json
        echo "Verificando os primeiros 10 caracteres de token.json:"
        head -c 10 token.json

    # Passo 6: Gerar e Fazer Upload do Vídeo
    - name: Generate and Upload Video
      run: |
        source venv/bin/activate
        echo ">>> pip freeze debug:"
        pip freeze

        # 1) Gera vídeo
        python scripts/main.py \
          --gemini-api "$GEMINI_API_KEY" \
          --youtube-channel "$YOUTUBE_CHANNEL_ID" \
          --pixabay-api "$PIXABAY_API_KEY"

        # 2) Faz Upload no YouTube
        python scripts/upload_youtube.py \
          --video-file "video_final.mp4" \
          --client-secret-file "client_secret.json" \
          --token-file "token.json" \
          --title "Curiosities Title" \
          --description "Curious facts" \
          --category "22" \
          --tags "curiosities,facts"

      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
