name: Build e Executar Scripts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # <-- Isso habilita o botão "Run workflow" na página de Actions do repositório

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install & Run
        run: |
          echo "IMAGEMAGICK_BINARY=/bin/false" >> $GITHUB_ENV
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          echo ">>> pip freeze debug:"
          pip freeze
          python scripts/main.py
