name: Pipeline de Automação

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixar o Código
      - name: Checkout
        uses: actions/checkout@v3

      # Passo 2: Definir Python 3.9
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Passo 3: Criar venv, instalar dependências e rodar script em um só passo
      - name: Install & Run
        run: |
          # Criar e ativar ambiente virtual
          python -m venv venv
          source venv/bin/activate

          # Instalar dependências
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir moviepy

          # Desativar o ImageMagick
          echo "IMAGEMAGICK_BINARY=/bin/false" >> $GITHUB_ENV

          # Executar o script principal
          python scripts/main.py
        shell: bash
