name: Automação YouTube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Criar Pasta de Credenciais
        run: mkdir -p credentials

      - name: Decodificar Credenciais OAuth JSON
        run: |
          echo "${{ secrets.OAUTH_CREDENTIALS }}" | base64 --decode | sed '1s/^\xEF\xBB\xBF//' > credentials/client_secret.json

      - name: Instalar jq para Validar JSON
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Validar Estrutura do client_secret.json
        run: jq empty credentials/client_secret.json

      - name: Verificar Presença do Campo 'token_uri' no client_secret.json
        run: |
          if jq -e '.token_uri' credentials/client_secret.json > /dev/null; then
            echo "'token_uri' está presente."
          else
            echo "Erro: Campo 'token_uri' está ausente no client_secret.json."
            exit 1
          fi

      - name: Verificar Presença do Campo 'client_email' no client_secret.json
        run: |
          if jq -e '.client_email' credentials/client_secret.json > /dev/null; then
            echo "'client_email' está presente."
          else
            echo "Erro: Campo 'client_email' está ausente no client_secret.json."
            exit 1
          fi

      - name: Executar Script de Automação
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          source venv/bin/activate
          # Verifica se todas as variáveis de ambiente estão definidas
          if [ -z "$GEMINI_API_KEY" ] || [ -z "$YOUTUBE_CHANNEL_ID" ] || [ -z "$PIXABAY_API_KEY" ] || [ -z "$CLIENT_ID" ] || [ -z "$CLIENT_SECRET" ] || [ -z "$REFRESH_TOKEN" ]; then
            echo "Erro: Uma ou mais variáveis de ambiente estão vazias."
            exit 1
          fi
          # Executa o script principal com os parâmetros necessários
          python scripts/main.py \
            --gemini-api "${GEMINI_API_KEY}" \
            --youtube-channel "${YOUTUBE_CHANNEL_ID}" \
            --pixabay-api "${PIXABAY_API_KEY}" \
            --quantidade 3  # Atualizado para 3 para atender aos requisitos da API

      - name: Finalizar Job
        if: always()
        run: echo "Job finalizado."
